// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace sewer56_archives_nx.Net.Sys
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "sewer56_archives_nx";



        [DllImport(__DllName, EntryPoint = "it_works", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int it_works();


    }



}
